@startuml
left to right direction

title Singleton Örneği

class Singleton {
  -{static} instance : Singleton
  -sayi : Number
  -Singleton()
  +{static}getInstance() : Singleton
  +getSayi() : Number
}

Singleton --> Singleton : instance

@enduml