@startuml
left to right direction

title Uçak Sistemi


class Kanat {
 +şekil
}

class Kule {
  +bildir()
}

class YolcuUçağı {
  +durum
  +yolcular[]
  +kuleyeBilgiVer()
}

' İki pilot aynı yemekleri yemezler, bu yüzden bu fonksiyon her pilot için override edilecek. 
interface IPilot {
  yemekYe()
}

class AnaPilot {
  +uçağıKaldır()
  +uçağıİndir()
  +yemekYe()
}

class KoPilot {
  +bilgiVer()
  +yemekYe()
}

class Pilot {
  +durumuDenetle()
}

class Hostes {
  +yiyecekGetir()
}

class Görevli {
  +anonsYap()
}

YolcuUçağı *-- "1..*" Koltuk
YolcuUçağı *-- "2" Kanat
YolcuUçağı o-- "0..*" EğlenceSistemi

YolcuUçağı <.. Pilot : "<<use>>"

IPilot <|.. KoPilot
IPilot <|.. AnaPilot

AnaPilot --o Pilot
KoPilot --o Pilot

Pilot --|> Görevli
Hostes --|> Görevli

Kule -- YolcuUçağı


@enduml